# Introduction to TensorFlows

In [1]:
import tensorflow as tf
g = tf.Graph()
with g.as_default() as g:
  tf_x            = tf.constant([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  col_sum         = tf.reduce_sum(tf_x, axis=0)
  row_sum         = tf.reduce_sum(tf_x, axis=1)
  col_sum_times_2 = col_sum*2
  row_sum_times_2 = row_sum*2
  
with tf.Session(graph=g) as sess:
  csum_2 = sess.run(col_sum_times_2)
  rsum_2 = sess.run(row_sum_times_2)
print('csum_2:\n', csum_2)
print('rsum_2:\n', rsum_2)

csum_2:
 [18. 24.]
rsum_2:
 [ 6. 14. 22.]


**Variables**: to store and update parameters
    Use TensorFlow's ***Variable***() constructor  which is similar ro ***Constant***()  
    



In [2]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  tf_x = tf_x +x
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  result = sess.run(tf_x)
  result = sess.run(tf_x)
print(result)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


To update and assign new values to variables, we use  TensorFlow's ***assign*** operation:
           assign(ref,val,.....)

---



In [5]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  result = sess.run(update_tf_x)
  result = sess.run(update_tf_x)
print(result)

[[3. 4.]
 [5. 6.]
 [7. 8.]]


**Placeholder** Variables:  to feed the graph with numerical values- Use ***feed_dict*** in active session\\

  Variables

    For parameters to learn
    Values can be derived from training
    Initial values are required (often random)

Placeholders

    Allocated storage for data (such as for image pixel data during a feed)
    Initial values are not required (but can be set, see tf.placeholder_with_default)


In [7]:
import tensorflow as tf
import numpy as np
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.placeholder(tf.float32,shape=(3,2))
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  #update_tf_x =  tf.assign(tf_x, tf_x+x)
  #tf_x = tf_x +x
  # multiply matrix
  matmul_tf_x =  tf.matmul(tf_x, tf.transpose(tf_x))
  update_tf_x =  tf_x+x
  
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  np_array = np.array([[1.,2.],[3.,4.],[5.,6.]])
  feed = {tf_x:np_array}
  
  output = sess.run(matmul_tf_x, feed_dict=feed)
  
  result1 = sess.run(tf_x, feed_dict= feed)
  result2 = sess.run(update_tf_x, feed_dict= feed)
print(output)
print(result1)
print(result2)

[[ 5. 11. 17.]
 [11. 25. 39.]
 [17. 39. 61.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[2. 3.]
 [4. 5.]
 [6. 7.]]


# **Saving** and **restoring** : we  use ***Saver*** class : tf.train.Saver()
   To save specify variables : tf.train.Saver([tf_x])


In [8]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
  saver = tf.train.Saver()
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  result = sess.run(update_tf_x)
  # save the model
  saver.save(sess, save_path='./my-model.ckpt')
print(result)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


 To restore our variables

In [9]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
  saver = tf.train.Saver()
with tf.Session(graph=g) as sess:
  saver.restore(sess, save_path='./my-model.ckpt')
  result = sess.run(update_tf_x)
  print(result)

W0706 14:56:32.411392 139879518762880 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


[[3. 4.]
 [5. 6.]
 [7. 8.]]


Example

In [10]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
  saver = tf.train.Saver()
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  for epoch in range(100):
    result = sess.run(update_tf_x)
    if not epoch %10:
      # save the model
      saver.save(sess, save_path='./my-model-multiple_ckpts.ckpt',global_step= epoch)

print(result)

W0706 14:56:47.013657 139879518762880 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.


[[101. 102.]
 [103. 104.]
 [105. 106.]]


In [11]:
with tf.Session(graph=g) as sess:
  saver.restore(sess, save_path='./my-model-multiple_ckpts.ckpt-90')
  result = sess.run(update_tf_x)
  print(result)

[[93. 94.]
 [95. 96.]
 [97. 98.]]


# **Naming** TensorFlow objects

In [0]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  #tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],dtype=tf.float32)
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
  saver = tf.train.Saver()
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  result = sess.run(update_tf_x)
  saver.save(sess, save_path='./my-model.ckpt')
  
print(result)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


In [0]:
with tf.Session(graph=g) as sess:
  saver.restore(sess, save_path='./my-model.ckpt')
  result = sess.run(update_tf_x)
  print(result)

INFO:tensorflow:Restoring parameters from ./my-model.ckpt
[[3. 4.]
 [5. 6.]
 [7. 8.]]


We reversed the order of tf_y and tf_x

In [0]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],dtype=tf.float32)
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float32)
  #tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
  saver = tf.train.Saver()
with tf.Session(graph=g) as sess:
  saver.restore(sess, save_path='./my-model.ckpt')
  result = sess.run(update_tf_x)
  print(result)

We give our variables specific names

In [0]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],name='tf_x_0',dtype=tf.float32)
  tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],name='tf_y_0',dtype=tf.float32)
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
  saver = tf.train.Saver()
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  result = sess.run(update_tf_x)
  saver.save(sess, save_path='./my-model.ckpt')
  
print(result)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


In [0]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],name='tf_y_0',dtype=tf.float32)
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],name='tf_x_0',dtype=tf.float32)
  
  x    = tf.constant(1.,dtype=tf.float32)
  # add constant to matrix:
  update_tf_x =  tf.assign(tf_x, tf_x+x)
  saver = tf.train.Saver()
with tf.Session(graph=g) as sess:
  saver.restore(sess, save_path='./my-model.ckpt')
  result = sess.run(update_tf_x)
  print(result)

INFO:tensorflow:Restoring parameters from ./my-model.ckpt
[[3. 4.]
 [5. 6.]
 [7. 8.]]


# **Control** **Flow** : if/else , while  : we use tf.*cond*()

In [0]:
import tensorflow as tf
addition = True
#addition = False
g=tf.Graph()
with g.as_default() as g:
  x = tf.placeholder(dtype=tf.float32,shape=None)
  if addition:
    y = x+1
  else:
    y = x-1
with tf.Session(graph=g) as sess:
  feed = {x:1.}
  output = sess.run(y, feed_dict=feed)
print('Output:\n', output)

Output:
 2.0


In [0]:
import tensorflow as tf
#addition = True
#addition = False
g=tf.Graph()
with g.as_default() as g:
  addition = tf.placeholder(dtype=tf.bool, shape=None)
  x = tf.placeholder(dtype=tf.float32,shape=None)
  y = tf.cond(addition,true_fn=lambda: tf.add(x,1.),false_fn=lambda: tf.subtract(x,1.))
with tf.Session(graph=g) as sess:
  feed = {addition:True,x:1.}
  output = sess.run(y, feed_dict=feed)
print('Output:\n', output)

Output:
 2.0


# TensorBoard

To visualize a computational graph

In [0]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],name='tf_x_0',dtype=tf.float32)
  tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],name='tf_y_0',dtype=tf.float32)
  output = tf_x + tf_y
  output = tf.matmul(tf.transpose(tf_x),output)
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  file_writer = tf.summary.FileWriter(logdir='logs/1',graph=g)
  result = sess.run(output)
  print(result)

 using name_scope()

In [0]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],name='tf_x_0',dtype=tf.float32)
  tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],name='tf_y_0',dtype=tf.float32)
  with tf.name_scope('addition'):
    output = tf_x + tf_y
  
  with tf.name_scope('matrix_multiplication'):
    output = tf.matmul(tf.transpose(tf_x),output)
  
with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  file_writer = tf.summary.FileWriter(logdir='logs/2',graph=g)
  result = sess.run(output)
  print(result)

In [0]:
import tensorflow as tf
g=tf.Graph()
with g.as_default() as g:
  some_value = tf.placeholder(dtype=tf.int32,shape=None,name='some_value')
  tf_x = tf.Variable([[1.,2.],[3.,4.],[5.,6.]],name='tf_x_0',dtype=tf.float32)
  tf_y = tf.Variable([[7.,8.],[9.,10.],[11.,12.]],name='tf_y_0',dtype=tf.float32)
  with tf.name_scope('addition'):
    output = tf_x + tf_y
  
  with tf.name_scope('matrix_multiplication'):
    output = tf.matmul(tf.transpose(tf_x),output)
  with tf.name_scope('update_tensor_x'):
    tf_const = tf.constant(2.,shape=None,name='some_const')
    updtae_tf_x = tf.assign(tf_x, tf_x*tf_const)
 # create summaries
tf.summary.scalar(name='some_value',tensor=some_value)
tf.summary.histogram(name='tf_x_values',values=tf_x)
merged_summary = tf.summary.merge_all()

with tf.Session(graph=g) as sess:
  sess.run(tf.global_variables_initializer())
  file_writer = tf.summary.FileWriter(logdir='logs/3',graph=g)
  
  for i in range(5):
    result, summary = sess.run([update_tf_x,merged_summary],feed_dict={some_value:i})
    file_writer.add_summary(summary=summary,global_step=i)
    file_writer.flush()
  